# This is a basic workflow to help you get started with Actions

name: Build with Docker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: startsWith(github.event.head_commit.message, '(ci)')
    strategy:
      matrix:
        target_os: [linux] # currently supported
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
      - name: Set up
        if: contains(${{ matrix.target_os }}, 'linux')
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          docker pull ghcr.io/telegramdesktop/tdesktop/centos_env
          docker tag ghcr.io/telegramdesktop/tdesktop/centos_env tdesktop:centos_env
      - name: Build ${{ matrix.target_os }} distribution
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
        run: bash ./icytea b --${{ matrix.target_os }}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          path: icyt/out/RelWithDebInfo
